[build.environment]
REACT_APP_SUPABASE_URL=https://leksqmkcaqjcgqfjavye.supabase.co
REACT_APP_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxla3NxbWtjYXFqY2dxZmphdnllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA1Mjk4NzksImV4cCI6MjA3NjEwNTg3OX0.vpyfzD3b4ATY6XeQ2Sd_2zNjG6WoaCBYC-qgCCIZ11s
REACT_APP_SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxla3NxbWtjYXFqY2dxZmphdnllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA1Mjk4NzksImV4cCI6MjA3NjEwNTg3OX0.vpyfzD3b4ATY6XeQ2Sd_2zNjG6WoaCBYC-qgCCIZ11s


[[redirects]]
from = "/*"
to = "/index.html"
status = 200

